"use client";
import Image from "next/image";
import { useEffect,useMemo,useState } from "react";

const treatments=[
 {name:"BelleTox",category:"Injectables",price:"₱195 / unit",duration:"30 min"},
 {name:"Fat Dissolving Injection",category:"Body Contouring",price:"From ₱995",duration:"45 min"},
 {name:"Laser Treatment",category:"Laser Care",price:"From ₱1,495",duration:"45 min"},
 {name:"Microneedling",category:"Skin Renewal",price:"From ₱2,995",duration:"60 min"},
 {name:"Très Belle Signature",category:"Facial Care",price:"₱795",duration:"60 min"},
 {name:"Crystal Aqua Belle",category:"Facial Care",price:"₱995",duration:"75 min"},
 {name:"Acne Clarity",category:"Facial Care",price:"₱1,995",duration:"75 min"},
 {name:"Glowing Drip",category:"IV Wellness",price:"₱1,595",duration:"60 min"}
];
const doctors=["Dr. Van Aldrin Ramos RN MD","Dr. Melvic Mae Roxas MD"];
const slots=["10:00 AM","11:00 AM","12:00 PM","1:00 PM","2:00 PM","3:00 PM","4:00 PM","5:00 PM","6:00 PM"];

export default function BookingModal({open,onClose}:{open:boolean;onClose:()=>void}){
 const [step,setStep]=useState(0),[doctor,setDoctor]=useState(doctors[0]),[treatment,setTreatment]=useState("");
 const [date,setDate]=useState(""),[time,setTime]=useState(""),[authGate,setAuthGate]=useState(false);
 const [viewMonth,setViewMonth]=useState(()=>new Date());
 const [details,setDetails]=useState({first:"",last:"",email:"",phone:"",birth:"",notes:""});
 useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
 useEffect(()=>{document.querySelector(".booking-content")?.scrollTo({top:0,behavior:"smooth"})},[step]);
 const selected=useMemo(()=>treatments.find(x=>x.name===treatment),[treatment]);
 const monday=date?new Date(date+"T12:00:00").getDay()===1:false;
 const minDate=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Manila"});
 const monthLabel=viewMonth.toLocaleDateString("en-PH",{month:"long",year:"numeric"});
 const calendarDays=useMemo(()=>{const y=viewMonth.getFullYear(),m=viewMonth.getMonth(),first=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:total},(_,i)=>{const day=i+1,key=y+"-"+String(m+1).padStart(2,"0")+"-"+String(day).padStart(2,"0");return{day,key,past:key<minDate,monday:new Date(y,m,day).getDay()===1}})]},[viewMonth,minDate]);
 const canNext=step===0?!!treatment:step===1?!!(details.first&&details.last&&details.email&&details.phone):step===2?!!(date&&time&&!monday):true;
 if(!open)return null;
 const next=()=>{if(!canNext)return;if(step<3)setStep(step+1);else setAuthGate(true)};
 return <div className="booking-overlay" role="dialog" aria-modal="true" aria-label="Book an appointment" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}>
  <div className="booking-modal">
   <header className="booking-header"><Image src="/images/tresbellelogo-removebg-preview.png" alt="Tres Belle" width={110} height={78}/><div><h2>Book an Appointment</h2><p>Plaza Esperanza · Santa Maria, Bulacan</p></div><button onClick={onClose} aria-label="Close booking">×</button></header>
   <div className="booking-steps">{["Visit & Treatment","Patient Details","Date & Time","Review"].map((label,i)=><div className={i===step?"active":i<step?"done":""} key={label}><b>{i<step?"✓":i+1}</b><span>{label}</span></div>)}</div>
   <div className="booking-content">
    {step===0&&<section className="booking-panel"><div className="booking-title"><span>01</span><div><h3>Choose your treatment</h3><p>Select a doctor and one service for your visit.</p></div></div><div className="doctor-choice"><label>Preferred doctor</label><select value={doctor} onChange={e=>setDoctor(e.target.value)}>{doctors.map(x=><option key={x}>{x}</option>)}</select></div><div className="treatment-layout"><div className="catalog-shell"><div className="catalog-head"><div><b>Treatment catalog</b><small>Add a procedure to your appointment.</small></div><span>{selected?"1 selected":"0 selected"}</span></div><div className="catalog-tabs"><b>All treatments</b><span>Facial care</span><span>Aesthetic</span><span>IV wellness</span></div><div className="treatment-catalog">{treatments.map(item=><button className={treatment===item.name?"selected":""} key={item.name} onClick={()=>setTreatment(item.name)}><span><small>{item.category}</small><strong>{item.name}</strong><em>◷ {item.duration}</em></span><span><b>{item.price}</b><i>{treatment===item.name?"✓ In cart":"＋ Add"}</i></span></button>)}</div></div><aside className="appointment-cart"><div className="cart-head"><span>▣</span><div><h4>Your appointment cart</h4><small>{selected?"1 item":"0 items"}</small></div>{selected&&<button onClick={()=>setTreatment("")}>Clear</button>}</div>{selected?<><div className="cart-item"><div><small>{selected.category}</small><strong>{selected.name}</strong><span>{selected.duration}</span></div><b>{selected.price}</b></div><div className="cart-details"><p><span>Treatments</span><b>{selected.price}</b></p><p className="cart-total"><strong>Estimated total</strong><strong>{selected.price}</strong></p></div><button className="cart-continue" onClick={()=>setStep(1)}>Continue <span>→</span></button><small className="cart-disclaimer">Final eligibility is confirmed by the doctor.</small></>:<div className="empty-cart"><b>＋</b><p>Your cart is empty</p><span>Browse treatments and add one to begin.</span></div>}</aside></div></section>}
    {step===1&&<section className="booking-panel"><div className="booking-title"><span>02</span><div><h3>Your details</h3><p>We’ll use these details for appointment updates.</p></div></div><div className="privacy-note"><b>Private patient information</b><span>For this proposal, details remain only in your browser and are not submitted.</span></div><div className="patient-form"><label>First name *<input value={details.first} onChange={e=>setDetails({...details,first:e.target.value})}/></label><label>Last name *<input value={details.last} onChange={e=>setDetails({...details,last:e.target.value})}/></label><label>Email address *<input type="email" value={details.email} onChange={e=>setDetails({...details,email:e.target.value})}/></label><label>Phone number *<input value={details.phone} placeholder="+63" onChange={e=>setDetails({...details,phone:e.target.value})}/></label><label>Date of birth<input type="date" value={details.birth} onChange={e=>setDetails({...details,birth:e.target.value})}/></label><label>Concerns / notes<textarea value={details.notes} onChange={e=>setDetails({...details,notes:e.target.value})} placeholder="Tell the doctor what you would like to discuss."/></label></div></section>}
    {step===2&&<section className="booking-panel"><div className="booking-title"><span>03</span><div><h3>Select date &amp; time</h3><p>Clinic hours: Tuesday–Sunday, 10:00 AM–7:00 PM. Monday closed.</p></div></div><div className="schedule-summary"><div><small>Doctor</small><strong>{doctor}</strong></div><div><small>Treatment</small><strong>{treatment}</strong></div><div><small>Location</small><strong>Plaza Esperanza</strong></div></div><div className="date-time-grid"><div className="calendar-card"><div className="calendar-title"><div><b>Choose a date</b><small>Select an open clinic day</small></div></div><div className="calendar-month"><button onClick={()=>setViewMonth(new Date(viewMonth.getFullYear(),viewMonth.getMonth()-1,1))}>‹</button><strong>{monthLabel}</strong><button onClick={()=>setViewMonth(new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,1))}>›</button></div><div className="calendar-grid">{["SU","MO","TU","WE","TH","FR","SA"].map(x=><b key={x}>{x}</b>)}{calendarDays.map((item,i)=>item?<button key={item.key} disabled={item.past||item.monday} className={date===item.key?"selected":""} onClick={()=>{setDate(item.key);setTime("")}}>{item.day}</button>:<span key={"blank"+i}/>)}</div></div><div className="time-card"><div className="calendar-title"><div><b>Choose a time</b><small>{date?"Available appointment slots":"Select a date to view availability"}</small></div></div>{date?<><div className="selected-date">{new Date(date+"T12:00:00").toLocaleDateString("en-PH",{weekday:"long",month:"long",day:"numeric"})}</div><div className="time-slots">{slots.map(slot=><button className={time===slot?"selected":""} key={slot} onClick={()=>setTime(slot)}>{slot}</button>)}</div></>:<div className="no-date"><b>□</b><strong>No date selected</strong><span>Choose an open date from the calendar.</span></div>}</div></div></section>}
    {step===3&&<section className="booking-panel review-panel"><div className="booking-title"><span>04</span><div><h3>Review your booking</h3><p>Confirm the information below before continuing.</p></div></div><div className="review-grid"><div><small>Patient</small><strong>{details.first} {details.last}</strong><span>{details.email}<br/>{details.phone}</span></div><div><small>Visit</small><strong>{treatment}</strong><span>{doctor}</span></div><div><small>Schedule</small><strong>{date&&new Date(date+"T12:00:00").toLocaleDateString("en-PH",{month:"long",day:"numeric",year:"numeric"})}</strong><span>{time}</span></div><div><small>Location</small><strong>Tres Belle Aesthetic Clinic</strong><span>2nd Floor Plaza Esperanza, Poblacion, Santa Maria, Bulacan</span></div></div><label className="booking-check"><input type="checkbox" required/> I understand this request is subject to clinic confirmation.</label></section>}
   </div>
   <footer className="booking-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><button className="primary" disabled={!canNext} onClick={next}>{step===3?"Continue":"Next"} →</button></footer>
   {authGate&&<div className="auth-gate"><div><button className="auth-close" onClick={()=>setAuthGate(false)}>×</button><span className="auth-icon">♙</span><small>One last step</small><h3>Save your booking</h3><p>Sign in or create a patient account to keep your treatment, schedule, and contact details. You’ll return to this review afterward.</p><button className="auth-primary">Sign in to continue</button><b>OR</b><button className="auth-secondary">Create patient account</button><em>Your information will be ready after you sign in.</em></div></div>}
  </div>
 </div>
}
